pipeline:
  name: Welcome Message
  identifier: Welcome_Message
  projectIdentifier: <input_project_name>
  orgIdentifier: <input_org_name>
  stages:
    - stage:
        name: First Stage
        description: Fix the 'Welcome message' step
        identifier: first_stage
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome message
                  identifier: welcome_message
                  spec:
                    connectorRef: account.Anonymous_Dockerhub
                    image: alpine:3
                    shell: Bash
                    command: |
                      echo "Welcome to Harness CI!"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
